Repository prgrms-web-devcourse-final-project/WEB1_2_Mallangs_FE, pull requests merged in 2024-12, with the labels that each got.

#42 TW-001 / 동물 구조 요청 글타래 작성 마크업
  src/assets/stylesheets/components/_threadRescueModal.scss
  src/assets/stylesheets/style.scss
  src/components/ThreadRescueModal.jsx
Labels: 🛠️ Feat

#46 컴포넌트 리팩토링
  src/assets/stylesheets/components/_birthdaySelector.scss
  src/assets/stylesheets/components/_completeButton.scss
  src/assets/stylesheets/components/_genderSelector.scss
  src/assets/stylesheets/components/_infoText.scss
  src/assets/stylesheets/components/_settingMallangs.scss
  src/assets/stylesheets/components/_threadRescueModal.scss
  src/assets/stylesheets/components/_toggleButton.scss
  src/assets/stylesheets/components/_typeSelector.scss
  src/assets/stylesheets/style.scss
  src/components/ThreadModal.jsx
  src/components/common/BirthdaySelector.jsx
  src/components/common/CompleteButton.jsx
  src/components/common/GenderSelector.jsx
  src/components/common/InfoText.jsx
  src/components/common/SettingMallangs.jsx
  src/components/common/ThreadModalCover.jsx
  src/components/common/ThreadRescueForm.jsx
  src/components/common/ToggleButton.jsx
  src/components/common/TypeSelector.jsx
  src/stores/rescueThreadStatus.js
Labels: ♻️ Refactor

#47 P_001 / 주 모달 출력과 내부 navigation 기능 추가
  .prettierrc
  index.html
  public/fonts/PretendardVariable.woff2
  public/images/liquid-efffect.svg
  src/assets/stylesheets/abstracts/_keyframes.scss
  src/assets/stylesheets/base/_default.scss
  src/assets/stylesheets/components/_areaInfoPanel.scss
  src/assets/stylesheets/components/_articleItem.scss
  src/assets/stylesheets/components/_chatRoomItem.scss
  src/assets/stylesheets/components/_mainModal.scss
  src/assets/stylesheets/components/_mainModalCover.scss
  src/assets/stylesheets/components/_markerCategory.scss
  src/assets/stylesheets/components/_notificationCard.scss
  src/assets/stylesheets/components/_signatureImage.scss
  src/assets/stylesheets/components/_totalSearch.scss
  src/assets/stylesheets/components/_userProfileCard.scss
  src/assets/stylesheets/layouts/_commons.scss
  src/assets/stylesheets/layouts/_headers.scss
  src/assets/stylesheets/pages/_mallangMap.scss
  src/assets/stylesheets/pages/_registerPage.scss
  src/assets/stylesheets/style.css
  src/assets/stylesheets/style.scss
  src/assets/stylesheets/themes/_defaultColor.scss
  src/components/MainModal.jsx
  src/components/MallangMap.jsx
  src/components/common/ChatRoomItem.jsx
  src/components/common/MainModalCover.jsx
  src/components/common/ModalDateSeparator.jsx
  src/components/common/ReceiveChatItem.jsx
  src/components/common/SendChatItem.jsx
  src/components/common/ThreadItem.jsx
  src/components/common/ToggleButton.jsx
  src/components/common/ToolTip.jsx
  src/components/layout/AreaInfoPanel.jsx
  src/components/layout/BaseLayout.jsx
  src/components/layout/Header.jsx
  src/components/layout/MarkerCategory.jsx
  src/components/layout/NotificationCard.jsx
  src/components/layout/TotalSearch.jsx
  src/components/layout/UserProfileCard.jsx
  src/datas/modalNavObject.json
  src/main.jsx
  src/pages/CommunityPage.jsx
  src/pages/ComponentMuseum.jsx
  src/pages/RegisterPage.jsx
  src/pages/UserArticles.jsx
  src/pages/UserChatList.jsx
  src/pages/UserChatRoom.jsx
  src/pages/UserProfile.jsx
  src/pages/UserReplies.jsx
  src/pages/UserReviews.jsx
  src/pages/UserThreads.jsx
  src/stores/AreaInfoStatus.js
  src/stores/modalStatus.js
  src/stores/notificationStatus.js
  src/utils/getLatestLocation.js
Labels: 🛠️ Feat, 🌈 Style

#48 M_001 / 말랑맵 글타래 작성 셀렉터 추가, 미 로그인 상태 헤더 마크업 추가
  index.html
  public/images/logo.png
  src/assets/images/login-background-image.png
  src/assets/images/logo.png
  src/assets/miscs/login-movie-0.mp4
  src/assets/stylesheets/abstracts/_keyframes.scss
  src/assets/stylesheets/components/_userProfileCard.scss
  src/assets/stylesheets/layouts/_commons.scss
  src/assets/stylesheets/layouts/_headers.scss
  src/assets/stylesheets/pages/_mallangMap.scss
  src/assets/stylesheets/style.css
  src/components/MallangMap.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/layout/UserProfileCard.jsx
  src/pages/LoginPage.jsx
  src/pages/RegisterPage.jsx
Labels: 🌈 Style

#52 M_001 / 비동기 요청을 위해 전역 query provider 적용 및 JSON 서버 데이터 요청 형식 정의
  src/api/threadApi.js
  src/assets/stylesheets/components/_mainModal.scss
  src/assets/stylesheets/components/_signatureImage.scss
  src/assets/stylesheets/components/_totalSearch.scss
  src/assets/stylesheets/components/_userProfileCard.scss
  src/assets/stylesheets/layouts/_footers.scss
  src/assets/stylesheets/layouts/_headers.scss
  src/assets/stylesheets/pages/_mallangMap.scss
  src/assets/stylesheets/style.css
  src/components/MainModal.jsx
  src/components/MallangMap.jsx
  src/components/common/SignatureImage.jsx
  src/components/layout/BaseLayout.jsx
  src/components/layout/MarkerCategory.jsx
  src/components/layout/TotalSearch.jsx
  src/components/layout/UserProfileCard.jsx
  src/datas/temp-current-user.json
  src/datas/temp-db.json
  src/main.jsx
  src/pages/ArticleDetailsPage.jsx
  src/pages/ArticleListPage.jsx
  src/pages/CommunityPage.jsx
  src/pages/ComponentMuseum.jsx
  src/pages/MissingDetailsPage.jsx
  src/pages/MissingListPage.jsx
Labels: 🛠️ Feat, ♻️ Refactor

#55 MP_001 / 실종 반려동물 신고 글타래 (보기)
  src/api/threadApi.js
  src/assets/stylesheets/base/_default.scss
  src/assets/stylesheets/components/_buttons.scss
  src/assets/stylesheets/components/_mainModal.scss
  src/assets/stylesheets/components/_mainModalCover.scss
  src/assets/stylesheets/components/_modalFormInput.scss
  src/assets/stylesheets/layouts/_commons.scss
  src/assets/stylesheets/pages/_missingReport.scss
  src/assets/stylesheets/pages/_placeInfo.scss
  src/assets/stylesheets/style.css
  src/assets/stylesheets/style.scss
  src/components/MainModal.jsx
  src/components/common/MainModalCover.jsx
  src/components/common/ModalFormInput.jsx
  src/components/common/StarRating.jsx
  src/components/layout/AreaInfoPanel.jsx
  src/datas/modalNavObject.json
  src/datas/temp-db.json
  src/main.jsx
  src/pages/CommunityPage.jsx
  src/pages/ComponentMuseum.jsx
  src/pages/MissingInfo.jsx
  src/pages/MissingSightingReport.jsx
  src/pages/PlaceInfo.jsx
  src/pages/PlaceMisinfoReport.jsx
  src/pages/PlaceReviewList.jsx
  src/pages/PlaceReviewWrite.jsx
  src/pages/ReplyList.jsx
  src/stores/modalStatus.js
Labels: 🛠️ Feat, 🌈 Style

#56 TW-001 / 동물 구조 요청 글타래 작성 컴포넌트 수정 및 기능 추가
  src/assets/stylesheets/components/_completeButton.scss
  src/assets/stylesheets/components/_dateTime.scss
  src/assets/stylesheets/components/_threadRescue.scss
  src/assets/stylesheets/style.scss
  src/components/MainModal.jsx
  src/components/MallangMap.jsx
  src/components/common/CompleteButton.jsx
  src/components/common/DateTime.jsx
  src/components/common/DiscoverySituation.jsx
  src/components/common/InputAddress.jsx
  src/components/common/TypeSelector.jsx
  src/pages/ThreadRescue.jsx
Labels: 🛠️ Feat, ♻️ Refactor

#60 TW_001 / 동물구조요청 글타래 작성 API 연결
  src/components/common/DateTime.jsx
  src/pages/ThreadRescue.jsx
Labels: 🛠️ Feat

#62 TW_003 / 사용자 위치 등록 글타래 작성
  src/assets/stylesheets/components/_singleInput.scss
  src/assets/stylesheets/pages/_threadPlace.scss
  src/assets/stylesheets/style.scss
  src/components/MainModal.jsx
  src/components/common/SingleInput.jsx
  src/pages/ThreadPlace.jsx
  src/pages/ThreadRescue.jsx
Labels: 🛠️ Feat

#67 ✨ Feat: 지도 선택시 글타래 주소 반환 로직 추가 #65
  src/api/axios.js
  src/api/threadApi.js
  src/components/MallangMap.jsx
  src/pages/ThreadRescue.jsx
  src/stores/locationStore.js
Labels: 🛠️ Feat

#64 로그인, 회원가입 (ID 없음) / 마크업 정리 및 디자인 요소 추가
  package-lock.json
  package.json
  public/images/logo.png
  public/images/temp-logo.png
  src/assets/images/logo.png
  src/assets/images/marker-alpha.png
  src/assets/images/marker-beta.png
  src/assets/images/marker-gamma.png
  src/assets/stylesheets/abstracts/_keyframes.scss
  src/assets/stylesheets/components/_chatRoomItem.scss
  src/assets/stylesheets/components/_emptyList.scss
  src/assets/stylesheets/layouts/_commons.scss
  src/assets/stylesheets/pages/_loginPage.scss
  src/assets/stylesheets/pages/_registerPage.scss
  src/assets/stylesheets/style.css
  src/components/MainModal.jsx
  src/components/MallangMap.jsx
  src/components/layout/UserProfileCard.jsx
  src/datas/example thread.json
  src/datas/temp-db.json
  src/pages/ComponentMuseum.jsx
  src/pages/LoginPage.jsx
  src/pages/MissingInfo.jsx
  src/pages/PlaceInfo.jsx
  src/pages/RegisterPage.jsx
  src/pages/UserArticles.jsx
  src/pages/UserChatList.jsx
  src/pages/UserProfile.jsx
  src/pages/UserReplies.jsx
  src/pages/UserReviews.jsx
  src/stores/modalStatus.js
  src/utils/getLatestLocation.js
Labels: 🌈 Style

#68 Feat/ 주소 입력 컴포넌트에 상태값 받아오도록 수정 #65
  src/components/common/InputAddress.jsx
  src/pages/ThreadRescue.jsx
  src/stores/locationStore.js
Labels: 🛠️ Feat

#69 TW_002 / 실종 반려 동물 신고 작성 글타래
  src/api/threadApi.js
  src/assets/stylesheets/pages/_threadMissingReport.scss
  src/assets/stylesheets/style.scss
  src/components/common/GenderSelector.jsx
  src/pages/ThreadMissingReport.jsx
Labels: 🛠️ Feat

#71 Edit Mode 커버 작동 수정
  package-lock.json
  package.json
  public/images/logo.png
  src/assets/stylesheets/components/_buttons.scss
  src/assets/stylesheets/components/_mainModalCover.scss
  src/assets/stylesheets/components/_multipleImageUploader.scss
  src/assets/stylesheets/layouts/_commons.scss
  src/assets/stylesheets/style.css
  src/assets/stylesheets/style.scss
  src/components/common/MainModalCover.jsx
  src/components/common/MultipleImageUploader.jsx
  src/pages/MissingInfo.jsx
  src/pages/MissingSightingReport.jsx
  src/pages/UserChatRoom.jsx
  src/stores/modalStatus.js
Labels: ♻️ Refactor

#73 ✨ Feat: 맵 마커 API 연동 #72
  package-lock.json
  package.json
  src/api/threadApi.js
  src/components/MallangMap.jsx
Labels: 🛠️ Feat

#74 ✨ Feat: 업체/시설 글타래 기능 구현 #29
  src/api/threadApi.js
  src/api/userApi.js
  src/datas/modalNavObject.json
  src/pages/PlaceInfo.jsx
Labels: 🛠️ Feat

#75 H_001 / 구조 요청 글타래 조회
  src/api/threadApi.js
  src/components/common/DiscoverySituation.jsx
  src/pages/RescueDetails.jsx
  src/pages/ThreadPlace.jsx
Labels: 🛠️ Feat

#80 댓글 수정 모드 토글 / 수정 기능 붙이기 완료
  public/images/placeholder-paw.png
  src/api/threadApi.js
  src/assets/stylesheets/components/_mainModal.scss
  src/assets/stylesheets/components/_replyItem.scss
  src/assets/stylesheets/components/_userLocationMap.scss
  src/assets/stylesheets/layouts/_commons.scss
  src/assets/stylesheets/pages/_registerPage.scss
  src/assets/stylesheets/style.css
  src/assets/stylesheets/style.scss
  src/components/MainModal.jsx
  src/components/common/ImageGallery.jsx
  src/components/common/MainModalCover.jsx
  src/components/common/MultipleImageUploader.jsx
  src/components/common/ReplyItem.jsx
  src/components/common/TernsOfService.jsx
  src/components/common/UserProfileImage.jsx
  src/pages/ComponentMuseum.jsx
  src/pages/PlaceInfo.jsx
  src/pages/PlaceReviewList.jsx
  src/pages/RegisterPage.jsx
  src/pages/ReplyList.jsx
  src/pages/Test.jsx
  src/pages/UserIgnoreList.jsx
  src/pages/UserThreads.jsx
Labels: ♻️ Refactor

#82 헤더 비어있는 메뉴 제거
  src/components/MainModal.jsx
  src/components/MallangMap.jsx
  src/components/layout/Header.jsx
Labels: ⚙️ Chore

#85 모달 내부 탭 이동 Fix
  src/components/MainModal.jsx
  src/components/common/MainModalCover.jsx
  src/datas/modalNavObject.json
Labels: 🐛 Fix

#87 잔업처리반
  src/components/MallangMap.jsx
  src/components/common/MainModalCover.jsx
  src/pages/ThreadMissingReport.jsx
  src/pages/ThreadPlace.jsx
  src/pages/ThreadRescue.jsx
  src/stores/titleStatus.js
Labels: 🛠️ Feat, 🐛 Fix
